In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("dataset/customer_shopping_behavior.csv")
data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [3]:
data.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
5045,913,24,Male,Hoodie,Clothing,56.0,Arkansas,M,Green,Winter,3.4,Yes,Next Day Air,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,Backpack,Accessories,53.0,Iowa,M,Gold,Spring,3.4,No,Standard,No,31.0,Debit Card,Weekly
5047,3572,70,Female,Skirt,Clothing,27.0,North Dakota,M,White,Summer,3.2,No,Standard,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,Sneakers,Footwear,52.0,Maryland,L,Gold,Summer,4.6,No,Standard,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,Blouse,Clothing,71.0,Maine,M,Cyan,Summer,3.3,No,Free Shipping,No,5.0,Bank Transfer,Every 3 Months

In [4]:
data.shape

(5050, 17)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [6]:
data.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [7]:
data.select_dtypes(include=["object"]).describe()

,Gender,Item Purchased,Category,Location,Size,Color,Season,Subscription Status,Shipping Type,Discount Applied,Payment Method,Frequency of Purchases
count,5050,5050,5050,5050,4680,5050,5050,5050,5050,5050,5050,5050
unique,3,30,5,54,4,25,5,2,6,2,6,7
top,Male,Shirt,Clothing,New York,M,Black,Spring,No,Standard,No,Credit Card,Monthly
freq,3018,320,2130,337,1981,404,1280,3462,1213,2789,954,946

In [8]:
# Check for null values
data.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [9]:
# Check for duplicates
data.duplicated().sum()

np.int64(50)

# Data Cleaning

In [10]:
clean_data = data.copy()

In [11]:
clean_data["Item Purchased"].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [12]:
clean_data["Category"].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [13]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [14]:
clean_data.groupby('Category')['Item Purchased'].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [15]:
correct_mapping = {
    # Clothing
    "T-shirt":"Clothing", "Shirt": "Clothing", "Shorts": "Clothing",
    "Hoodie": "Clothing", "Pants": "Clothing", "Socks": "Clothing",
    "Jeans": "Clothing", "Blouse": "Clothing", "Skirt": "Clothing",
    "Sweater": "Clothing", "Dress": "Clothing",

    # Accessories
    "Sunglasses": "Accessories", "Gloves": "Accessories", "Jewelry": "Accessories", "Hat": "Accessories",
    "Handbag": "Accessories", "Backpack": "Accessories", "Belt": "Accessories", "Scarf": "Accessories", "Bag": "Accessories",

    # Electronics
    "Laptop": "Electronics", "Phone": "Electronics", "Headphones": "Electronics", "Watch": "Electronics",

    # Footwear
    "Shoes": "Footwear", "Sandals": "Footwear", "Sneakers": "Footwear", "Boots": "Footwear",

    # Outwear
    "Coat": "Outwear", "Jacket": "Outwear"
}

In [16]:
clean_data['Category'] = clean_data['Item Purchased'].map(correct_mapping)
clean_data.groupby("Category")["Item Purchased"].unique()

Category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outwear                                                                              [Coat, Jacket]
Name: Item Purchased, dtype: object

In [17]:
clean_data.groupby('Category')['Size'].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outwear             [XL, L, S, M]
Name: Size, dtype: object

In [18]:
clean_data.groupby('Item Purchased')['Size'].unique()

Item Purchased
Backpack           [M, S, L, XL]
Bag           [M, L, nan, XL, S]
Belt               [M, S, XL, L]
Blouse             [M, L, S, XL]
Boots              [L, M, XL, S]
Coat               [XL, M, S, L]
Dress              [XL, M, L, S]
Gloves             [L, M, S, XL]
Handbag            [S, XL, M, L]
Hat                [M, L, S, XL]
Headphones    [S, M, nan, L, XL]
Hoodie             [M, L, S, XL]
Jacket             [L, S, M, XL]
Jeans              [L, M, XL, S]
Jewelry            [L, XL, M, S]
Laptop        [nan, M, S, XL, L]
Pants              [L, M, XL, S]
Phone         [nan, L, S, M, XL]
Sandals            [M, S, L, XL]
Scarf              [M, L, S, XL]
Shirt         [M, XL, L, S, nan]
Shoes         [M, L, nan, XL, S]
Shorts             [S, M, L, XL]
Skirt              [S, L, M, XL]
Sneakers           [S, M, L, XL]
Socks              [M, XL, L, S]
Sunglasses         [M, L, S, XL]
Sweater            [M, S, L, XL]
T-shirt            [XL, M, S, L]
Watch         [nan, M, L, XL, S]
Name: Size, dtype: object

### Treating Category

In [19]:
# Treating null values or replacing all values in the Electronic Category
clean_data.loc[clean_data['Category']=='Electronics', 'Size']='Not Applicable'

In [20]:
# Treating null values or replacing all values in the Accessories Category
clean_data.loc[clean_data['Category']=='Accessories', 'Size']='Free Size'

In [21]:
# Treating null values or replacing all values in the Footwear Category
clean_data.loc[clean_data['Category']=='Footwear','Size']='Not Available'

In [22]:
# Treating null values in the Clothing Category
clean_data.loc[(clean_data['Category']=='Clothing') & (clean_data['Size'].isnull()),'Size'] = clean_data.loc[data['Category']=='Clothing']['Size'].mode()[0]

In [23]:
clean_data.groupby('Category')['Size'].unique()

Category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outwear           [XL, L, S, M]
Name: Size, dtype: object

### Treating Review Rating

In [24]:
clean_data['Review Rating'] = clean_data['Review Rating'].fillna(clean_data.groupby('Item Purchased')['Review Rating'].transform('mean')).round(1)

### Treating Previous Purchased

In [25]:
clean_data['Previous Purchases'] = clean_data['Previous Purchases'].fillna(0)

### Treating Purchase Amount (USD)

In [26]:
clean_data['Purchase Amount (USD)'] = clean_data['Purchase Amount (USD)'].fillna(clean_data.groupby('Item Purchased')['Purchase Amount (USD)'].transform('mean')).round(2)

In [27]:
clean_data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [28]:
# Remove Duplicates
clean_data = clean_data.drop_duplicates(subset=['Customer ID'], keep='first')

### Renaming the Headers

In [29]:
clean_data.columns = clean_data.columns.str.replace(" ","_")
clean_data.columns = clean_data.columns.str.lower()

In [30]:
clean_data = clean_data.rename(columns={"purchase_amount_(usd)": "purchase_amount_usd"})

In [31]:
clean_data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

# Connect to PostgreSQL

In [32]:
import sys
print(sys.executable)

C:\Users\deepa\AppData\Local\Programs\Python\Python313\python.exe

In [33]:
!{sys.executable} -m pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in C:\Users\deepa\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in C:\Users\deepa\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in C:\Users\deepa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\deepa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
import psycopg2
from sqlalchemy import create_engine
from decouple import config

# 1. Define connection parameters
db_user = config("DB_USER")
db_password = config("DB_PSWD")
db_host = config("DB_HOST")
db_port = config("DB_PORT")
db_name = config("DB_NAME")

# 2. Create SQLAlchemy engine for pandas
engine = create_engine(f"postgresql+psycopg2://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}")

# 3. Save DataFrame to PostgreSQL
table_name = "customer_behaviour_analysis"
clean_data.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data saved successfully to PostgreSQL!")

ModuleNotFoundError: No module named 'decouple'